### ISSUE TITLE
Configurar metabase e subir banco dados

### ISSUE THREAD

**Issue by lpirola** [Mutirao/Bibip#15]

**Comment by lpirola** [comment]
Ao tentar restaurar o banco acontece o seguinte erro:

> [1] 43522 segmentation fault  pg_restore -f my.sql natuur_bm-18Ago2016.backup

O metabase está configurado em http://metabase.culturalivre.org

O formato desse backup está em modo binário, seria possível conseguir o arquivo em formato SQL?

**Comment by uira** [comment]
@lpirola Tá em formato de backup. Tu tentou fazer restore?

**Comment by lpirola** [comment]
@uira Sim, está dando o erro de "segmentation fault. O arquivo está usando a versão 9.4.8 e esse pode ser o problema pois estou usando o 9.5 no meu computador.

Vou tentar importar usando essa versão específica mas vai dar mais trabalho e não tenho tanta certeza que irá dar certo.
