### ISSUE TITLE
Criar Campo de Cronograma no Módulo de Editais do Mapas Culturais

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/Bibip#4]
**Criar um novo tipo de campo**, com o nome de cronograma, na seção de projetos do Mapa Cultural. Esse campo contem três entradas em cada linha, uma de texto, e duas de datas (ver anexo 1) para o usuário preencher. Para o editor, as opções de configuração do campo são: nome do campo, descrição do campo e seleção da condição do preenchimento obrigatório (ver anexo 2). O usuário pode adicionar mais linhas.

**Referências:**
Github do MapasCutlurais: 
https://github.com/Mutirao/mapasculturais

Guia do Desenvolvedor do Mapas Culturais
https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_developer_guide.md

**Tempo:**
Prazo para a conclusão do sprint: 17-10-16.

**Comment by gshiki** [comment]
Três dúvidas : 

1) Onde e como é feito o mapeamento das entidades no código? 

2) Quem é o responsável pelo translation dos objetos?

3) Provavelmente a resposta da pergunta 1 e 2 seriam suficientes mas : Como criar uma nova entidade no código e mapear?

**Comment by gshiki** [comment]
Mais uma : 

4) Qual o fluxo de chamada de uma view? Desde a requisição, passando pelo controller até a resposta.

**Comment by Andreqlp** [comment]
atividade não completada, alteração na demanda
