### ISSUE TITLE
Login Cidadão_Missão 1

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/Bibip#5]
**Criar ambiente de desenvolvimento** do login cidadão no servidor do Mutirão e customizar o tema para o estado do Ceará. 

_Bônus 1:_ criar uma arquivo compartilhado e documentar o que foi instalado no servidor.

**Ferramentas:**
Aceitando a missão você terá acesso a um servidor do mutirão. 

**Referências:**
Login Cidadão: http://logincidadao.org.br/  
https://github.com/Mutirao/login-cidadao 

**Tempo:**
Prazo para a conclusão do sprint: 12-09-16. 
Dedicação estimada: 20h (horários a definir caso a caso)

**Recompensa:** 
R$500,00 para a entrega concluída. Em caso de não conclusão no prazo previsto, poderá ser avaliada uma extensão do prazo ou pagamento parcial em função do que for entregue, desde que previamente acertado.

**Comment by Andreqlp** [comment]
Respostas do Lucas Pirola as qusetões da Cristina.
- Que tecnologias já são usadas no site? - Linux, Apache, Mysql ou Postgres, PHP, ela pode ter uma ideia visitando o repositório no github do login-cidadao ou o próprio fork do Mutirao;
- Que linguagens são utilizadas? PHP com Symphony principalmente e Javascript e css para interface
- Como posso ter acesso ao servidor? Precisamos dar acesso a ela ao SSH, ela vai precisar ter conhecimento de uso de um servidor linux.
- O que caracteriza para vocês um ambiente de desenvolvimento? Ambiente com o login cidadão funcionando completamente, com envio de email, cadastro de client. Ela pode seguir a documentação já existente dentro do repositório.

**Comment by lpirola** [comment]
Com a correção do certificado SSL, o LC passou a funcionar no seguinte endereço: https://lc.culturalivre.org/
